DROP DATABASE IF EXISTS;

CREATE DATABASE burger_db;

USE burger_db;

CREATE TABLE burger (
    id INT AUTO_INCREMENT NOT NULL,
    burger VARCHAR(30) NOT NULL,
    devoured BOOLEAN NOT NULL
);

SELECT * FROM burger;